services:
  - name: mein-web-service
    type: web
    platform: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py
    port: 5000  
    runtime:
      version: "3.10.12" 